import Head from 'next/head'
import { ReactElement } from 'react'
import { Footer } from '@/components/common/Footer/Footer'
import { Header } from '@/components/common/Header/Header'

type LayoutProps = Required<{
  readonly children: ReactElement
}>

export const BaseLayout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>uzulab</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        {children}
        <Footer />
      </main>
    </>
  )
}
