export const DUMMY_TAGS = [
  {
    id: 13,
    count: 1,
    description: '',
    link: 'https://ryotanakahara.jp/sys/archives/tag/app',
    name: 'app',
    slug: 'app',
    taxonomy: 'post_tag',
    meta: [],
    _links: {
      self: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags/13' }],
      collection: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags' }],
      about: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/taxonomies/post_tag' }],
      'wp:post_type': [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/posts?tags=13' }],
      curies: [{ name: 'wp', href: 'https://api.w.org/{rel}', templated: true }],
    },
  },
  {
    id: 5,
    count: 6,
    description: '',
    link: 'https://ryotanakahara.jp/sys/archives/tag/logo',
    name: 'logo',
    slug: 'logo',
    taxonomy: 'post_tag',
    meta: [],
    _links: {
      self: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags/5' }],
      collection: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags' }],
      about: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/taxonomies/post_tag' }],
      'wp:post_type': [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/posts?tags=5' }],
      curies: [{ name: 'wp', href: 'https://api.w.org/{rel}', templated: true }],
    },
  },
  {
    id: 4,
    count: 1,
    description: '',
    link: 'https://ryotanakahara.jp/sys/archives/tag/product',
    name: 'product',
    slug: 'product',
    taxonomy: 'post_tag',
    meta: [],
    _links: {
      self: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags/4' }],
      collection: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags' }],
      about: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/taxonomies/post_tag' }],
      'wp:post_type': [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/posts?tags=4' }],
      curies: [{ name: 'wp', href: 'https://api.w.org/{rel}', templated: true }],
    },
  },
  {
    id: 10,
    count: 1,
    description: '',
    link: 'https://ryotanakahara.jp/sys/archives/tag/video',
    name: 'video',
    slug: 'video',
    taxonomy: 'post_tag',
    meta: [],
    _links: {
      self: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags/10' }],
      collection: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags' }],
      about: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/taxonomies/post_tag' }],
      'wp:post_type': [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/posts?tags=10' }],
      curies: [{ name: 'wp', href: 'https://api.w.org/{rel}', templated: true }],
    },
  },
  {
    id: 12,
    count: 4,
    description: '',
    link: 'https://ryotanakahara.jp/sys/archives/tag/web',
    name: 'web',
    slug: 'web',
    taxonomy: 'post_tag',
    meta: [],
    _links: {
      self: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags/12' }],
      collection: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/tags' }],
      about: [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/taxonomies/post_tag' }],
      'wp:post_type': [{ href: 'https://ryotanakahara.jp/sys/wp-json/wp/v2/posts?tags=12' }],
      curies: [{ name: 'wp', href: 'https://api.w.org/{rel}', templated: true }],
    },
  },
]
export const EMPTY_TAGS = [
  {
    id: 0,
    count: 0,
    description: '',
    link: '',
    name: '',
    slug: '',
    taxonomy: '',
    meta: [],
    _links: {
      self: [{ href: '' }],
      collection: [{ href: '' }],
      about: [{ href: '' }],
      'wp:post_type': [{ href: '' }],
      curies: [{ name: '', href: '', templated: true }],
    },
  },
  {
    id: 0,
    count: 0,
    description: '',
    link: '',
    name: '',
    slug: '',
    taxonomy: '',
    meta: [],
    _links: {
      self: [{ href: '' }],
      collection: [{ href: '' }],
      about: [{ href: '' }],
      'wp:post_type': [{ href: '' }],
      curies: [{ name: '', href: '', templated: true }],
    },
  },
  {
    id: 0,
    count: 0,
    description: '',
    link: '',
    name: '',
    slug: '',
    taxonomy: '',
    meta: [],
    _links: {
      self: [{ href: '' }],
      collection: [{ href: '' }],
      about: [{ href: '' }],
      'wp:post_type': [{ href: '' }],
      curies: [{ name: '', href: '', templated: true }],
    },
  },
]
